# This is the developer's -*-Makefile-*-, not the user's makefile.
# Do not use it unless you know exactly what you do!

THISFILE = Makefile.devel
LN = ln -s
RM = rm -f

# ============ Rules that require cross-compilation tools ============

HOST = i486-linux
CPU = i386
GCC = gcc
GCCFLAGS = -O2 -fno-omit-frame-pointer -DHAVE_LONG_LONG_INT
SED = sed
CROSS_TOOL = cross

precompiled : \
  vacall-i386-macro.S \
  vacall-m68k.mit.S vacall-m68k.motorola.S \
  vacall-mipseb-macro.S vacall-mipsel-macro.S vacall-mipsn32eb-macro.S vacall-mipsn32el-macro.S vacall-mips64eb-macro.S vacall-mips64el-macro.S \
  vacall-sparc-macro.S vacall-sparc64-macro.S
# Old rules
# vacall-alpha.s vacall-hppa.s vacall-arm-macro.S vacall-armel.s vacall-powerpc-aix.s vacall-powerpc-sysv4.s vacall-powerpc-macos.s vacall-powerpc64.s vacall-ia64.s vacall-x86_64-macro.S


vacall-i386-linux.s : vacall-i386.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) i386-linux gcc -V 3.1 $(GCCFLAGS) -D__i386__ -S vacall-i386.c -o vacall-i386-linux.s

vacall-i386-macro.S : vacall-i386-linux.s ../common/asm-i386.sh $(THISFILE)
	(echo '#include "asm-i386.h"' ; sed -e '/\.align.*,0x90$$/d' < vacall-i386-linux.s | ../common/asm-i386.sh | sed -e 's/vacall_function/C(vacall_function)/g') > vacall-i386-macro.S


vacall-m68k-linux.s : vacall-m68k.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) m68k-linux gcc -V 3.1 $(GCCFLAGS) -D__m68k__ -S vacall-m68k.c -o vacall-m68k-linux.s

vacall-m68k-sun.s : vacall-m68k.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) m68k-sun gcc -V 3.1 $(GCCFLAGS) -D__m68k__ -S vacall-m68k.c -o vacall-m68k-sun.s

vacall-m68k.mit.S : vacall-m68k-sun.s ../common/asm-m68k.sh $(THISFILE)
	(echo '#include "asm-m68k.h"' ; ../common/asm-m68k.sh mit < vacall-m68k-sun.s) > vacall-m68k.mit.S

vacall-m68k.motorola.S : vacall-m68k-linux.s ../common/asm-m68k.sh $(THISFILE)
	(echo '#include "asm-m68k.h"' ; ../common/asm-m68k.sh motorola < vacall-m68k-linux.s | sed -e 's/vacall_function/C(vacall_function)/g') > vacall-m68k.motorola.S


vacall-mipseb-linux.s : vacall-mips.c vacall.h.in $(THISFILE)
# For references to global symbols: -mno-explicit-relocs ensures a syntax that the IRIX assembler understands.
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=32 -meb -mno-explicit-relocs $(GCCFLAGS) -D__mips__ -S vacall-mips.c -o vacall-mipseb-linux.s

vacall-mipseb-macro.S : vacall-mipseb-linux.s ../common/asm-mips.sh $(THISFILE)
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mipseb-linux.s) > vacall-mipseb-macro.S

vacall-mipsel-linux.s : vacall-mips.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=32 -mel -mno-explicit-relocs $(GCCFLAGS) -D__mips__ -S vacall-mips.c -o vacall-mipsel-linux.s

vacall-mipsel-macro.S : vacall-mipsel-linux.s ../common/asm-mips.sh $(THISFILE)
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mipsel-linux.s) > vacall-mipsel-macro.S

vacall-mipsn32eb-linux.s : vacall-mipsn32.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=n32 -meb $(GCCFLAGS) -D__mipsn32__ -S vacall-mipsn32.c -o vacall-mipsn32eb-linux.s

vacall-mipsn32eb-macro.S : vacall-mipsn32eb-linux.s ../common/asm-mips.sh $(THISFILE)
	$(SED) -e 's/\$$sp,\$$sp,\([-]*\)192/$$sp,$$sp,\1256/' < vacall-mipsn32eb-linux.s > vacall-mipsn32eb-linux-hacked.s
	if cmp vacall-mipsn32eb-linux.s vacall-mipsn32eb-linux-hacked.s > /dev/null; then echo "Postprocessing hack no longer applies." 1>&2; exit 1; fi
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mipsn32eb-linux-hacked.s) > vacall-mipsn32eb-macro.S
	$(RM) vacall-mipsn32eb-linux-hacked.s

vacall-mipsn32el-linux.s : vacall-mipsn32.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=n32 -mel $(GCCFLAGS) -D__mipsn32__ -S vacall-mipsn32.c -o vacall-mipsn32el-linux.s

vacall-mipsn32el-macro.S : vacall-mipsn32el-linux.s ../common/asm-mips.sh $(THISFILE)
	$(SED) -e 's/\$$sp,\$$sp,\([-]*\)192/$$sp,$$sp,\1256/' < vacall-mipsn32el-linux.s > vacall-mipsn32el-linux-hacked.s
	if cmp vacall-mipsn32el-linux.s vacall-mipsn32el-linux-hacked.s > /dev/null; then echo "Postprocessing hack no longer applies." 1>&2; exit 1; fi
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mipsn32el-linux-hacked.s) > vacall-mipsn32el-macro.S
	$(RM) vacall-mipsn32el-linux-hacked.s

vacall-mips64eb-linux.s : vacall-mips64.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=64 -meb $(GCCFLAGS) -D__mips64__ -S vacall-mips64.c -o vacall-mips64eb-linux.s

vacall-mips64eb-macro.S : vacall-mips64eb-linux.s ../common/asm-mips.sh $(THISFILE)
	$(SED) -e 's/\$$sp,\$$sp,\([-]*\)224/$$sp,$$sp,\1288/' < vacall-mips64eb-linux.s > vacall-mips64eb-linux-hacked.s
	if cmp vacall-mips64eb-linux.s vacall-mips64eb-linux-hacked.s > /dev/null; then echo "Postprocessing hack no longer applies." 1>&2; exit 1; fi
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mips64eb-linux-hacked.s) > vacall-mips64eb-macro.S
	$(RM) vacall-mips64eb-linux-hacked.s

vacall-mips64el-linux.s : vacall-mips64.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) mips64-linux gcc -V 4.0.2 -mabi=64 -mel $(GCCFLAGS) -D__mips64__ -S vacall-mips64.c -o vacall-mips64el-linux.s

vacall-mips64el-macro.S : vacall-mips64el-linux.s ../common/asm-mips.sh $(THISFILE)
	$(SED) -e 's/\$$sp,\$$sp,\([-]*\)224/$$sp,$$sp,\1288/' < vacall-mips64el-linux.s > vacall-mips64el-linux-hacked.s
	if cmp vacall-mips64el-linux.s vacall-mips64el-linux-hacked.s > /dev/null; then echo "Postprocessing hack no longer applies." 1>&2; exit 1; fi
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < vacall-mips64el-linux-hacked.s) > vacall-mips64el-macro.S
	$(RM) vacall-mips64el-linux-hacked.s


vacall-sparc-linux.s : vacall-sparc.c vacall.h.in $(THISFILE)
	$(CROSS_TOOL) sparc-linux gcc -V 3.1 $(GCCFLAGS) -D__sparc__ -S vacall-sparc.c -o vacall-sparc-linux.s

vacall-sparc-macro.S : vacall-sparc-linux.s ../common/asm-sparc.sh $(THISFILE)
	(echo '#include "asm-sparc.h"' ; ../common/asm-sparc.sh < vacall-sparc-linux.s | sed -e 's/vacall_function/C(vacall_function)/g') > vacall-sparc-macro.S

vacall-sparc64-linux.s : vacall-sparc64.c vacall.h.in $(THISFILE)
# For references to global symbols:
# - -mcmodel=medlow uses 2 instructions, but the code does not work on Solaris (error "ld: fatal: relocation error: R_SPARC_HI22").
# - -mcmodel=medmid uses 3 instructions, but the code still makes some assumptions about the address space.
# - -mcmodel=medany uses 4 instructions.
	$(CROSS_TOOL) sparc64-linux gcc -V 4.0.2 -mcmodel=medany $(GCCFLAGS) -D__sparc64__ -S vacall-sparc64.c -o vacall-sparc64-linux.s

vacall-sparc64-macro.S : vacall-sparc64-linux.s ../common/asm-sparc.sh $(THISFILE)
	(echo '#include "asm-sparc.h"' ; ../common/asm-sparc.sh < vacall-sparc64-linux.s | sed -e 's/vacall_function/C(vacall_function)/g') > vacall-sparc64-macro.S


vacall-alpha.s : vacall-alpha.c vacall.h.in $(THISFILE)
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -D__alpha__ -S vacall-alpha.c -o vacall-alpha-temp.s
	cat < vacall-alpha-temp.s > vacall-alpha.s
	$(RM) vacall-alpha-temp.s

vacall-hppa.s : vacall-hppa.c vacall.h.in $(THISFILE)
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -D__hppa__ -S vacall-hppa.c -o vacall-hppa.s

vacall-arm-macro.S : vacall-arm.c vacall.h.in ../common/asm-arm.sh $(THISFILE)
	$(GCC) -V 2.6.3 -b arm-acorn-riscix $(GCCFLAGS) -D__arm__ -S vacall-arm.c -o vacall-arm.s
	(echo '#include "asm-arm.h"' ; ../common/asm-arm.sh < vacall-arm.s) > vacall-arm-macro.S
	$(RM) vacall-arm.s

vacall-armel.s : vacall-armel.c vacall.h.in $(THISFILE)
	$(GCC) $(GCCFLAGS) -D__arm__ -D__ARMEL__ -DHAVE_LONG_LONG -fomit-frame-pointer -S vacall-armel.c -o vacall-armel.s

vacall-powerpc-aix.s : vacall-powerpc.c vacall.h.in $(THISFILE)
	$(GCC) -V 2.95.2 -b rs6000 -mno-power -mno-power2 -mno-powerpc -mnew-mnemonics $(GCCFLAGS) -D__powerpc__ -S vacall-powerpc.c -o vacall-powerpc-aix.s

vacall-powerpc-sysv4.s : vacall-powerpc.c vacall.h.in $(THISFILE)
	$(GCC) -V 2.95.2 -b ppc-linux -mno-power -mno-power2 -mno-powerpc $(GCCFLAGS) -D__powerpc__ -S vacall-powerpc.c -o vacall-powerpc-sysv4.s

vacall-powerpc-macos.s : vacall-powerpc.c vacall.h.in $(THISFILE)
	$(GCC) -V 3.3.2 -b powerpc-darwin $(GCCFLAGS) -D__powerpc__ -S vacall-powerpc.c -o vacall-powerpc-macos.s

vacall-powerpc64.s : vacall-powerpc64.c vacall.h.in $(THISFILE)
	/cross/powerpc64-linux-tools/bin/powerpc64-linux-gcc $(GCCFLAGS) -D__powerpc64__ -S vacall-powerpc64.c -o vacall-powerpc64.s

vacall-ia64.s : vacall-ia64.c vacall.h.in $(THISFILE)
	$(GCC) -V 2.9-ia64-000216 -b ia64-hp-linux $(GCCFLAGS) -D__ia64__ -S vacall-ia64.c -o vacall-ia64.s

vacall-x86_64-linux.s : vacall-x86_64.c vacall.h.in $(THISFILE)
	$(GCC) -V 3.2.2 -b x86_64-suse-linux $(GCCFLAGS) -D__x86_64__ -S vacall-x86_64.c -o vacall-x86_64-linux.s

vacall-x86_64-macro.S : vacall-x86_64-linux.s ../common/asm-x86_64.sh $(THISFILE)
	(echo '#include "asm-x86_64.h"' ; ../common/asm-x86_64.sh < vacall-x86_64-linux.s | sed -e 's/vacall_function/C(vacall_function)/g') > vacall-x86_64-macro.S

# --------------- Rules for debugging test failures ---------------

tests : tests-i386.s tests-m68k.s tests-mips.s tests-sparc.s tests-alpha.s tests-hppa.s tests-arm.s tests-powerpc.s tests-powerpc64.s tests-ia64.s tests-x86_64.s
	true

tests-i386.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.7.2 -b i486-linuxaout $(GCCFLAGS) -I/usr/include -D__i386__ -S tests.c -o tests-i386.s
	$(RM) vacall.h

tests-m68k.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.95.2 -b m68k-sun $(GCCFLAGS) -I/usr/include -D__m68k__ -S tests.c -o tests-m68k.s
	$(RM) vacall.h

tests-mips.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.95.2 -b mips-sgi $(GCCFLAGS) -I/usr/include -D__mips__ -S tests.c -o tests-mips.s
	$(RM) vacall.h

tests-sparc.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.95.2 -b sparc-sun $(GCCFLAGS) -I/usr/include -D__sparc__ -S tests.c -o tests-sparc.s
	$(RM) vacall.h

tests-alpha.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -I/usr/include -D__alpha__ -S tests.c -o tests-alpha.s
	$(RM) vacall.h

tests-hppa.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -I/usr/include -D__hppa__ -S tests.c -o tests-hppa.s
	$(RM) vacall.h

tests-arm.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.6.3 -b arm-acorn-riscix $(GCCFLAGS) -I/usr/include -D__arm__ -S tests.c -o tests-arm.s
	$(RM) vacall.h

tests-powerpc.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.95.2 -b rs6000 $(GCCFLAGS) -I/usr/include -D__powerpc__ -S tests.c -o tests-powerpc.s
	$(RM) vacall.h

tests-powerpc64.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	/cross/powerpc64-linux-tools/bin/powerpc64-linux-gcc $(GCCFLAGS) -I/usr/include -D__powerpc64__ -S tests.c -o tests-powerpc64.s
	$(RM) vacall.h

tests-ia64.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 2.9-ia64-000216 -b ia64-hp-linux $(GCCFLAGS) -I/usr/include -D__ia64__ -S tests.c -o tests-ia64.s
	$(RM) vacall.h

tests-x86_64.s : tests.c vacall.h.in
	$(LN) vacall.h.in vacall.h
	$(GCC) -V 3.2.2 -b x86_64-suse-linux $(GCCFLAGS) -I/usr/include -D__x86_64__ -S tests.c -o tests-x86_64.s
	$(RM) vacall.h
