# This is the developer's -*-Makefile-*-, not the user's makefile.
# Do not use it unless you know exactly what you do!

RM = rm -f

# ============ Rules that require cross-compilation tools ============

HOST = i486-linux
CPU = i386
GCC = gcc
GCCFLAGS = -O2 -fomit-frame-pointer
CPP = $(GCC) -E
CROSS_TOOL = cross
ASPREFIX = /usr1/gnu/lib

precompiled : proto-i386.s proto-m68k.s proto-mips.s proto-mipsn32.s proto-mips64.s proto-sparc.s proto-sparc64.s proto-alpha.s proto-hppa.s proto-arm.s proto-powerpc-aix.s proto-powerpc-sysv4.s proto-powerpc-macos.s proto-powerpc64-aix.s proto-ia64.c proto-x86_64.c \
      cache-sparc-macro.S cache-alpha.s cache-hppa.s cache-powerpc-sysv4.s cache-powerpc-macos.s

proto-i386.s : proto.c
	$(GCC) -V 2.7.2 -b i486-linuxaout $(GCCFLAGS) -D__i386__ -S proto.c -o $@

proto-m68k.s : proto.c
	$(GCC) -V egcs-2.91.57 -b m68k-sun $(GCCFLAGS) -D__m68k__ -S proto.c -o $@

proto-mips.s : proto.c
	$(GCC) -V 2.95.2 -b mips-sgi $(GCCFLAGS) -D__mips__ -S proto.c -o $@ -mabicalls

proto-mipsn32.s : proto.c
	$(GCC) -V 2.95.2 -b mips-sgi-irix6 $(GCCFLAGS) -D__mipsn32__ -S proto.c -o $@ -mabicalls

proto-mips64.s : proto64.c
	$(GCC) -V 2.95.2 -b mips-sgi -mips3 -mlong64 $(GCCFLAGS) -D__mips64__ -S proto64.c -o $@ -mabicalls

proto-sparc.s : proto.c
	$(GCC) -V 2.95.2 -b sparc-sun $(GCCFLAGS) -D__sparc__ -S proto.c -o $@

proto-sparc64.s : proto64.c
	sparc64-linux-gcc -V 2.95.2 -b sparc64-linux $(GCCFLAGS) -D__sparc64__ -S proto64.c -o $@

proto-alpha.s : proto64.c
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -D__alpha__ -S proto64.c -o $@

proto-hppa.s : proto.c
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -D__hppa__ -S proto.c -o $@

proto-arm.s : proto.c
	$(CROSS_TOOL) arm-linux gcc -V 3.1 $(GCCFLAGS) -fno-omit-frame-pointer -D__arm__ -S proto.c -o $@

proto-powerpc-aix.s : proto.c
	$(GCC) -V 2.95.2 -b rs6000 -mno-power -mno-power2 -mno-powerpc -mnew-mnemonics $(GCCFLAGS) -D__powerpc__ -S proto.c -o $@

proto-powerpc-sysv4.s : proto.c
	$(GCC) -V 2.95.2 -b ppc-linux -mno-power -mno-power2 -mno-powerpc $(GCCFLAGS) -D__powerpc__ -S proto.c -o $@

proto-powerpc-macos.s : proto.c
	$(GCC) -V 3.3.2 -b powerpc-darwin $(GCCFLAGS) -D__powerpc__ -S proto.c -o $@

proto-powerpc64-aix.s : proto64.c
	$(CROSS_TOOL) powerpc64-linux gcc $(GCCFLAGS) -D__powerpc64__ -S proto64.c -o $@

proto-ia64.s : proto64.c
	$(GCC) -V 2.9-ia64-000216 -b ia64-hp-linux $(GCCFLAGS) -D__ia64__ -S proto64.c -o $@

proto-x86_64.s : proto64.c
	$(GCC) -V 3.2.2 -b x86_64-suse-linux $(GCCFLAGS) -D__x86_64__ -S proto64.c -o $@

cache-sparc-macro.S : cache-sparc.c ../../common/asm-sparc.sh
	$(GCC) -V 2.95.2 -b sparc-sun $(GCCFLAGS) -D__sparc__ -S $< -o cache-sparc.s
	(echo '#include "asm-sparc.h"' ; ../../common/asm-sparc.sh < cache-sparc.s) > cache-sparc-macro.S
	$(RM) cache-sparc.s

cache-alpha.s : cache-alpha.c
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -D__alpha__ -S $< -o $@

cache-hppa.s : cache-hppa.c
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -D__hppa__ -S $< -o $@

cache-powerpc-sysv4.s : cache-powerpc.c
	$(GCC) -V 2.95.2 -b ppc-linux -mno-power -mno-power2 -mno-powerpc $(GCCFLAGS) -D__powerpc__ -S $< -o $@

cache-powerpc-macos.s : cache-powerpc.c
	$(GCC) -V 3.3.2 -b powerpc-darwin $(GCCFLAGS) -D__powerpc__ -S $< -o $@

tramp-i386.o : tramp-i386.s
	$(ASPREFIX)/i486-linux/bin/as tramp-i386.s -o $@

tramp-m68k.o : tramp-m68k.s
	$(ASPREFIX)/m68k-linux/bin/as tramp-m68k.s -o $@

tramp-mips.o : tramp-mips.s
	$(ASPREFIX)/mips-linux/bin/as tramp-mips.s -o $@

tramp-mips64.o : tramp-mips64.s
	$(ASPREFIX)/mips-linux/bin/as -mips64 -mabi=64 tramp-mips64.s -o $@

tramp-sparc.o : tramp-sparc.s
	$(ASPREFIX)/sparc-sun/bin/as tramp-sparc.s -o $@

tramp-sparc64.o : tramp-sparc64.s
	$(ASPREFIX)/sparc64-linux/bin/as tramp-sparc64.s -o $@

tramp-alpha.o : tramp-alpha.s
	$(ASPREFIX)/alpha-linux/bin/as tramp-alpha.s -o $@

tramp-hppa.o : tramp-hppa.s
	$(ASPREFIX)/hppa1.0-hpux/bin/as tramp-hppa.s -o $@

tramp-arm.o : tramp-arm.s
	$(CROSS_TOOL) arm-linux as tramp-arm.s -o $@

tramp-powerpc-old.o : tramp-powerpc-old.s
	$(ASPREFIX)/rs6000/bin/as tramp-powerpc-old.s -o $@

tramp-powerpc-sysv4.o : tramp-powerpc-sysv4.s
	$(ASPREFIX)/ppc-linux/bin/as tramp-powerpc-sysv4.s -o $@

tramp-ia64.o : tramp-ia64.s
	/nue/usr/ia64-hp-linux/bin/as tramp-ia64.s -o $@

tramp-x86_64.o : tramp-x86_64.s
	$(ASPREFIX)/x86_64-linux/bin/as tramp-x86_64.s -o $@

tramp-s390.o : tramp-s390.s
	$(ASPREFIX)/s390-ibm-linux/bin/as tramp-s390.s -o $@
