# This is the developer's -*-Makefile-*-, not the user's makefile.
# Do not use it unless you know exactly what you do!

LN = ln -s
RM = rm -f

# ============ Rules that require cross-compilation tools ============

HOST = i486-linux
CPU = i386
GCC = gcc
GCCFLAGS = -O2 -fomit-frame-pointer
SED = sed

precompiled : avcall-i386-macro.S avcall-m68k.mit.S avcall-m68k.mot.s avcall-m68k-amiga.s avcall-mips-macro.S avcall-mipsn32-macro.S avcall-mips64-macro.S avcall-sparc-macro.S avcall-sparc64-macro.S avcall-alpha.s avcall-hppa.s avcall-arm-macro.S avcall-armel-macro.S avcall-powerpc-aix.s avcall-powerpc-sysv4.s avcall-powerpc-macos.s avcall-powerpc64.s avcall-powerpc64le.s avcall-ia64.s avcall-x86_64-macro.S

avcall-i386-macro.S : avcall-i386.c avcall.h.in ../common/asm-i386.sh
	$(GCC) -V 2.7.2 -b i486-linuxaout $(GCCFLAGS) -D__i386__ -fno-omit-frame-pointer -S avcall-i386.c -o avcall-i386.s
	(echo '#include "asm-i386.h"' ; sed -e '/\.align.*,0x90$$/d' < avcall-i386.s | ../common/asm-i386.sh) > avcall-i386-macro.S
	$(RM) avcall-i386.s

avcall-m68k.mit.S : avcall-m68k.c avcall.h.in ../common/asm-m68k.sh
	$(GCC) -V 2.95.2 -b m68k-sun $(GCCFLAGS) -D__m68k__ -S avcall-m68k.c -o avcall-m68k.mit.s
	(echo '#include "asm-m68k.h"' ; ../common/asm-m68k.sh < avcall-m68k.mit.s) > avcall-m68k.mit.S
	$(RM) avcall-m68k.mit.s

avcall-m68k.mot.s : avcall-m68k.c avcall.h.in
	$(GCC) -V 2.95.2 -b m68k-linux $(GCCFLAGS) -D__m68k__ -S avcall-m68k.c -o avcall-m68k.mot.s

avcall-m68k-amiga.s : avcall-m68k-amiga.c avcall.h.in
	$(GCC) -V 2.95.2 -b m68k-sun -m68000 $(GCCFLAGS) -D__m68k__ -DAMIGA -S avcall-m68k-amiga.c -o avcall-m68k-amiga.s

avcall-mips-macro.S : avcall-mips.c avcall.h.in ../common/asm-mips.sh
	$(GCC) -V 2.95.2 -b mips-sgi $(GCCFLAGS) -D__mips__ -fno-omit-frame-pointer -S avcall-mips.c -o avcall-mips.s
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < avcall-mips.s) > avcall-mips-macro.S
	$(RM) avcall-mips.s

avcall-mipsn32-macro.S : avcall-mipsn32.c avcall.h.in ../common/asm-mips.sh
	$(GCC) -V 2.95.2 -b mips-sgi-irix6 $(GCCFLAGS) -D__mipsn32__ -fno-omit-frame-pointer -S avcall-mipsn32.c -o avcall-mipsn32.s
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < avcall-mipsn32.s) > avcall-mipsn32-macro.S
	$(RM) avcall-mipsn32.s

avcall-mips64-macro.S : avcall-mips64.c avcall.h.in ../common/asm-mips.sh
	$(GCC) -V 2.95.2 -b mips-sgi -mips3 -mlong64 $(GCCFLAGS) -U__mips__ -D__mips64__ -fno-omit-frame-pointer -S avcall-mips64.c -o avcall-mips64.s
	(echo '#include "asm-mips.h"' ; ../common/asm-mips.sh < avcall-mips64.s) > avcall-mips64-macro.S
	$(RM) avcall-mips64.s

avcall-sparc-macro.S : avcall-sparc.c avcall.h.in ../common/asm-sparc.sh
	$(GCC) -V 2.95.2 -b sparc-sun $(GCCFLAGS) -D__sparc__ -S avcall-sparc.c -o avcall-sparc.s
	(echo '#include "asm-sparc.h"' ; ../common/asm-sparc.sh < avcall-sparc.s) > avcall-sparc-macro.S
	$(RM) avcall-sparc.s

avcall-sparc64-macro.S : avcall-sparc64.c avcall.h.in ../common/asm-sparc64.sh
	sparc64-linux-gcc -V 2.95.2 -b sparc64-linux $(GCCFLAGS) -D__sparc64__ -S avcall-sparc64.c -o avcall-sparc64.s
	(echo '#include "asm-sparc.h"' ; ../common/asm-sparc64.sh < avcall-sparc64.s) > avcall-sparc64-macro.S
	$(RM) avcall-sparc64.s

# Patrick Bridges says that on Linux/Alpha, avcall-alpha.s compiled with "-O"
# works but compiled with "-O2" doesn't work.
avcall-alpha.s : avcall-alpha.c avcall.h.in
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -O1 -D__alpha__ -S avcall-alpha.c -o avcall-alpha-temp.s
	$(SED) -e '/ldgp/d' < avcall-alpha-temp.s > avcall-alpha.s
	$(RM) avcall-alpha-temp.s

avcall-hppa.s : avcall-hppa.c avcall.h.in
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -D__hppa__ -S avcall-hppa.c -o avcall-hppa-temp.s
	$(SED) -e 's/120/1060/g' < avcall-hppa-temp.s > avcall-hppa.s
	$(RM) avcall-hppa-temp.s

avcall-arm-macro.S : avcall-arm.c avcall.h.in ../common/asm-arm.sh
	$(GCC) -V 2.6.3 -b arm-acorn-riscix $(GCCFLAGS) -D__arm__ -S avcall-arm.c -o avcall-arm.s
	(echo '#include "asm-arm.h"' ; ../common/asm-arm.sh < avcall-arm.s) > avcall-arm-macro.S
	$(RM) avcall-arm.s

avcall-armel.s : avcall-armel.c avcall.h.in
	$(GCC) $(GCCFLAGS) -D__arm__ -S avcall-armel.c -o avcall-armel.s

avcall-powerpc-aix.s : avcall-powerpc.c avcall.h.in
	$(GCC) -V 2.95.2 -b rs6000 -mno-power -mno-power2 -mno-powerpc -mnew-mnemonics $(GCCFLAGS) -D__powerpc__ -S avcall-powerpc.c -o avcall-powerpc-aix.s

avcall-powerpc-sysv4.s : avcall-powerpc.c avcall.h.in
	$(GCC) -V 2.95.2 -b ppc-linux -mno-power -mno-power2 -mno-powerpc $(GCCFLAGS) -D__powerpc__ -S avcall-powerpc.c -o avcall-powerpc-sysv4.s

avcall-powerpc-macos.s : avcall-powerpc.c avcall.h.in
	$(GCC) -V 3.3.2 -b powerpc-darwin $(GCCFLAGS) -D__powerpc__ -S avcall-powerpc.c -o avcall-powerpc-macos.s

avcall-powerpc64.s : avcall-powerpc64.c avcall.h.in
	/cross/powerpc64-linux-tools/bin/powerpc64-linux-gcc $(GCCFLAGS) -D__powerpc64__ -S avcall-powerpc64.c -o avcall-powerpc64.s

avcall-powerpc64le.s : avcall-powerpc64le.c avcall.h.in
	$(GCC) $(GCCFLAGS) -D__powerpc64__ -D__powerpc64le__ -S avcall-powerpc64le.c -o avcall-powerpc64le.s

avcall-ia64.s : avcall-ia64.c avcall.h.in
	$(GCC) -V 2.9-ia64-000216 -b ia64-hp-linux $(GCCFLAGS) -D__ia64__ -S avcall-ia64.c -o avcall-ia64.s

avcall-x86_64-linux.s : avcall-x86_64.c avcall.h.in
	$(GCC) -V 3.2.2 -b x86_64-suse-linux $(GCCFLAGS) -D__x86_64__ -S avcall-x86_64.c -o avcall-x86_64-linux.s

avcall-x86_64-macro.S : avcall-x86_64-linux.s ../common/asm-x86_64.sh
	(echo '#include "asm-x86_64.h"' ; ../common/asm-x86_64.sh < avcall-x86_64-linux.s) > avcall-x86_64-macro.S

# --------------- Rules for debugging test failures ---------------

tests : tests-i386.s tests-m68k.s tests-mips.s tests-sparc.s tests-alpha.s tests-hppa.s tests-arm.s tests-powerpc.s tests-ia64.s tests-x86_64.s
	true

tests-i386.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.7.2 -b i486-linuxaout $(GCCFLAGS) -I/usr/include -D__i386__ -S tests.c -o tests-i386.s
	$(RM) avcall.h

tests-m68k.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.95.2 -b m68k-sun $(GCCFLAGS) -I/usr/include -D__m68k__ -S tests.c -o tests-m68k.s
	$(RM) avcall.h

tests-mips.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.95.2 -b mips-sgi $(GCCFLAGS) -I/usr/include -D__mips__ -S tests.c -o tests-mips.s
	$(RM) avcall.h

tests-sparc.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.95.2 -b sparc-sun $(GCCFLAGS) -I/usr/include -D__sparc__ -S tests.c -o tests-sparc.s
	$(RM) avcall.h

tests-alpha.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.7.2 -b alpha-dec-osf $(GCCFLAGS) -I/usr/include -D__alpha__ -S tests.c -o tests-alpha.s
	$(RM) avcall.h

tests-hppa.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.6.3 -b hppa1.0-hpux $(GCCFLAGS) -I/usr/include -D__hppa__ -S tests.c -o tests-hppa.s
	$(RM) avcall.h

tests-arm.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.6.3 -b arm-acorn-riscix $(GCCFLAGS) -I/usr/include -D__arm__ -S tests.c -o tests-arm.s
	$(RM) avcall.h

tests-powerpc.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.95.2 -b rs6000 $(GCCFLAGS) -I/usr/include -D__powerpc__ -S tests.c -o tests-powerpc.s
	$(RM) avcall.h

tests-ia64.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 2.9-ia64-000216 -b ia64-hp-linux $(GCCFLAGS) -I/usr/include -D__ia64__ -S tests.c -o tests-ia64.s
	$(RM) avcall.h

tests-x86_64.s : tests.c avcall.h.in
	$(LN) avcall.h.in avcall.h
	$(GCC) -V 3.2.2 -b x86_64-suse-linux $(GCCFLAGS) -I/usr/include -D__x86_64__ -S tests.c -o tests-x86_64.s
	$(RM) avcall.h
